apiVersion: v1
kind: ServiceAccount
metadata:
  name: funnel
  namespace: ${TES_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: arn:${AWS_PARTITION}:iam::${AWS_ACCOUNT_ID}:role/${TES_ROLE_NAME}