apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: funnel-db-pvc
  namespace: ${TES_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ${CINDER_STORAGE_CLASS}
